---
# This playbook provides VM orchestration on Amazon EC2
# most things set in vars directory in case you're wondering :)

- name: VM and Application Orchestration Demo
  hosts: localhost
  connection: local
  gather_facts: no
  ignore_errors: true

  roles:
    - { role: 'linux/provision', tags: ["instances", "linux"], when: ec2_os_type == 'linux' }
    - { role: 'windows/provision', tags: ["instances", "windows"], when: ec2_os_type == 'windows' }

- name: Configure common options across new Linux instances
  hosts: justcreatedlinux
  gather_facts: yes
  become: yes
  become_method: sudo

  roles:
    - linux/postcreate
    - { role: 'linux/apps/web', tags: ["apps", "linux"], when: ec2_instance_app == 'web' }
    # we can add more apps roles here if we wanted, or perhaps an array of apps would be better to loop through?

- name: Configure common options across new Windows instances
  hosts: justcreatedwindows
  gather_facts: no

  #roles:
  #  - windows/postcreate
