---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo

  roles:
    - common
