---
# This playbook does basic IIS stuff on Windows hosts

- name: IIS Web Code Deployment
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes

    - name: Start IIS service
      win_service:
        name: W3Svc
        state: started

    - name: Ensure git Installed
      win_chocolatey:
        name: git
        state: present

    - name: Deploy Web Code
      win_git:
        repo: 'https://gitlab.com/ffirg/AlienInvasion.git'
        dest: 'C:\Inetpub\wwwroot\'
        branch: devel
        recursive: yes
        replace_dest: yes
        accept_hostkey: yes