---
# This playbook does basic IIS stuff on Windows hosts

- name: IIS Web Code Deployment
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes

    - name: Start IIS service
      win_service:
        name: W3Svc
        state: started

    - name: Configure Client DNS
      win_dns_client:
        adapter_names: Ethernet
        ipv4_addresses:
        - 10.0.1.4
        - 8.8.8.8

    - name: Ensure git Installed
      win_chocolatey:
        name: git
        state: present

    - name: Deploy Web Code
      win_git:
        repo: 'https://gitlab.com/ffirg/AlienInvasion.git'
        dest: 'C:\inetpub\wwwroot\alieninvasion'
        branch: devel
        replace_dest: yes
        recursive: yes
        update: yes
        clone: yes
        accept_hostkey: yes