---
# This playbook does basic IIS stuff on Windows hosts

- name: IIS web deployment
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes

    - name: Start IIS service
      win_service:
        name: W3Svc
        state: started

    - name: Create website index.html
      win_copy:
        src: files/web.html
        dest: C:\Inetpub\wwwroot\index.html