---
- hosts: '{{ target | default("all") }}'
  gather_facts: no

  tasks:

  - name: Add a new event log for automation events
    win_eventlog:
      name: Automation
      sources:
        - ansible-actions
      state: present

  - name: Write an entry to the automation event log
    win_eventlog_entry:
      log: Automation
      source: ansible-actions
      event_id: 1
      message: "{{ tower_user_name}} just added this using {{ tower_job_template_name }}"