- hosts: '{{ target | default("all") }}'
  gather_facts: no

  vars:
    this: "{{lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')}}"

  tasks:

  - name: Add a new event log for automation events
    win_eventlog:
      name: Automation
      sources:
        - ansible-actions
      state: present

  - name: Write an entry to the automation event log
    win_eventlog_entry:
      log: Automation
      source: ansible-actions
      event_id: 1
      message: Just created this log using "{{ this }}".