---
# This playbook uses the win_get_url module to download a simple HTML file for IIS

- name: Demo Windows Web Services Creation
  hosts: all
  gather_facts: false

- name: Install/enable IIS
  import_playbook: enable_iis.yml
 
- name: Create web site content
  import_playbook: deploy_web_site.yml
