---
- hosts: idrac
  connection: local
  name: Get system inventory
  gather_facts: false

  collections:
  - dellemc.openmanage

  tasks:
  - name: Get system inventory.
    idrac_system_info:
      idrac_ip: "{{ inventory_hostname  }}"
      idrac_user: "{{ username }}"
      idrac_password: "{{ password }}"
      validate_certs: false
