- hosts: localhost
  gather_facts: false
  vars:
    fruits:
      - oranges
      
  tasks:
    - name: Check for apples...
      assert:
        that: >-
          'apples' in fruits
        msg: You have no apples
