- hosts: localhost
  gather_facts: false
  vars:
    fruits:
<<<<<<< HEAD
      - oranges
=======
      - lemons
>>>>>>> 767595d (slight mod)
      
  tasks:
    - name: Check for apples...
      assert:
        that: >-
          'apples' in fruits
        msg: You have no apples
