---

- name: Print order of hosts in each host group
  hosts: all
  gather_facts: no
  serial: 1

  tasks:
    - name: Print order of hosts in each host group in the inventory
      block:
        - name: Print all host groups
          debug:
            msg: "{{ groups }}"
      delegate_to: localhost
      run_once: yes
