---
- name: Create a RHEV based VM
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    rhvm: lnlabrhvm01.opstklab.local
    hostname: pgriffit-ansible-test1

  vars_prompt:
    - name: "username"
      prompt: "Enter RHEV-M username: "
      private: yes
    - name: "password"
      prompt: "Enter RHEV-M users password: "
      private: yes

  tasks:

    - name: Authenicate with RHV
      ovirt_auth:
        url: https://'{{rhvm}}'/ovirt-engine/api
        username: '{{ username }}@internal'
        password: "{{ password }}"

    - name: Create a VM called {{ hostname }}
      ovirt_vms:
        state: present
        name: '{{ hostname }}'
        template: pgriffit-rhel7-base-template
