---
- name: start Azure VMs
  hosts: localhost
  connection: local
  gather_facts: false
  ignore_errors: true

  vars:
    instances:
#     - { name: 'skylight-dc', rg: 'skylight-resource' }
      - { name: 'tower1', rg: 'core-infra' }

  tasks:
    - name: "start instances"
      azure_rm_virtualmachine:
        resource_group: "{{ item.rg }}"
        name: "{{ item.name }}"
        state: present
        started: true
      loop: "{{ instances }}"
      register: output
      until: output is not failed
      retries: 3
