- name: query domain for user account
  win_domain_user:
    name: "{{ username }}"
    state: query
  register: domainuserquery

- name: check domain membership
  assert:
    that:
      - "'present' in domainuserquery.state"
    success_msg: "{{ username }} is a DOMAIN account"
    fail_msg: "{{ username }} is not a DOMAIN member"
    quiet: true
  ignore_errors: true

- name: Domain user account changes
  include_role: 
    name: win-domain-user.yml
  when: domainuserquery.state == "present"
  tags: domain

- name: Local user account changes
  include_role: 
    name: win-local-user.yml
  when: domainuserquery.state == "absent"
  tags: local