---
# This playbook contains post VM creation tasks that will be run on all Linux nodes.
- hosts: tag_Name_just_created_linux
  become: yes
  become_method: sudo
  gather_facts: false

- name: Create ops user accounts
  user:
    name=bill comment="Bill Rogers" uid=1102 groups=wheel append=yes
    name=ted comment="Ted Wonderful" uid=1103 groups=wheel append=yes
