---
- name: Delete a vsphere ESXI VM
  hosts: localhost
  connection: local

  tasks:
    - name: Delete an ESXi VM Guest
      vsphere_guest:
        vcenter_hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        guest: '{{ hostname }}'
        state: absent
        force: yes
