---
- name: Setup an vsphere ESXI VM from a template
  hosts: localhost
  connection: local

  tasks:
    - name: Create an ESXi VM Guest From Template
      vsphere_guest:
        guest: tower-generated-vm
        from_template: yes
        template_src: tpl-rhel7-minimal
        cluster: Demonstrations
        esxi:
          datacenter: EMEA CloudLab
          hostname: cloud12-acc.gps.hst.ams2.redhat.com
