---
- name: Setup an Azure instance
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create Azure VM with defaults
      azure_rm_virtualmachine:
        resource_group: tower-demos-rg1
        name: '{{vm_name}}'
        vm_size: '{{vm_size}}'
        storage_account: towerdemos
        admin_username: '{{admin_username}}'
        admin_password: '{{admin_password}}'
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
