- name: Create GCP instance(s)
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    machine_type: n1-standard-1 # default
    image: debian-7
    project_id: redhat-examples

  tasks:
    - name: Launch instances
      gce:
          instance_names: ansible-example-vm
          machine_type: '{{ machine_type }}'
          image: '{{ image }}'
          #service_account_email: '{{ service_account_email }}'
          #credentials_file: '{{ credentials_file }}'
          project_id: '{{ project_id }}'
          tags: webserver
      register: gce

    - name: Wait for SSH to come up
      wait_for: host='{{ item.public_ip }}' port=22 delay=10 timeout=60
      with_items: '{{gce.instance_data}}'

    - name: Add host to groupname
      add_host: hostname='{{ item.public_ip }}' groupname=new_instances
      with_items: '{{gce.instance_data}}'

#- name: Manage new instances
#  hosts: new_instances
#  connection: ssh
#  sudo: True
#  roles:
#    - base_configuration
#    - production_server
