- hosts: hostA
  tasks:
    - name: Download to local download folder
      connection: local
      get_url:
        url: http://ipv4.download.thinkbroadband.com/5MB.zip
        dest: /opt/ansible_files/mbse/test.zip

    - name: copy file to folder
      become: yes
      copy: 
        src: /opt/ansible_files/mbse/test.zip
        dest: /tmp/test.zip
