---
- name: Linux Account Admin (we do nothing without a valid tag)
  hosts: web
  # we don't need any host facts, so disable to make run faster
  gather_facts: false
  become: yes
  tags: never

  tasks:

    - block:

        - name: Disable Local Linux User Account
          user:
            name: '{{ account|lower }}'
            password_lock: yes
            shell: /bin/false
            expires: 0

      rescue:
        - debug: msg='Oops! Something went wrong DISABLING the account - please investigate'

      always:
        - debug: msg='Tasks to disable Linux user account have been run'

      tags:
        - disable

    - block:

        - name: Delete Local Linux User Account
          user:
            name: '{{ account|lower }}'
            state: absent
            remove: yes

      rescue:
        - debug: msg='Oops! Something went wrong DELETING the account - please investigate'

      always:
        - debug: msg='Tasks to delete Linux user account have been run'

      tags:
        - delete