---
- name: RHV Discovery
  hosts: all

  tasks:

    - block:

      - name: Authenticate against RHVM
        ovirt_auth:
          # pass username/password in using Tower Survey
          url: 'https://lnlabrhvm01.opstklab.local/ovirt-engine/api'
          username: '{{ rhvm_username }}'
          password: '{{ rhvm_password }}'
          insecure: yes

      - name: List VMs
        ovirt_vms_facts:
          auth: "{{ ovirt_auth }}"

      always:
        - name: Always revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
