---
- name: Web Site Checks Rulebook
  hosts: all
  
  sources:
    - name: Are my key web sites operational
      ansible.eda.url_check:
        verify_ssl: false
        delay: 30 # seconds
        urls:
          - https://status.redhat.com
          #- http://loadofrubbishurl.com
        
  rules:
    - name: Alert if URL is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: "Default"
