---
- name: Check that URLs are Available
  hosts: localhost
  
  sources:
    - ansible.eda.url_check:
        verify_ssl: false
        delay: 30 # seconds
        urls:
          - https://status.redhat.com
          - http://loadofrubbishurl.com
        
  rules:
    - name: Alert if URL is down
      condition: event.url_check.status == 'down'
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: "Default"
