---
# tasks file for disk role

- name: Find large files
  command: find "{{ disk_path | default('/') }}" -size +{{ disk_min_size_check | default('1') }}M -ls
  register: output

- name: Output
  debug:
    var: output.stdout_lines
  when: output.stdout != ''
