---
- name: Deploy AlienInvasion Game
  hosts: tower-demos-rg1
  gather_facts: true
  become: true

  vars:
    git_branch: devel

  tasks:
    - name: Install Software Required
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - git
      tags: software

    - name: Git Clone Repo on to Web Servers
      git:
        repo: 'https://gitlab.com/ffirg/AlienInvasion.git'
        dest: /var/www/html/
        version: "{{ git_branch }}"
        force: yes
      tags: content

    - name: Start Web Services
      service:
        name: httpd
        state: started
      tags: service

    - name: Smoke Testing
      uri:
        url: "http://{{ ansible_host }}"

    - name: Smoke Testing
      uri:
        url: "http://{{ inventory_hostname['public_ip'] }}"