# vim:ft=ansible:
# setup namespaces/upload collections into containerized PAH
# turn verbose project syncing on
# call one of the collection things here
---
- hosts: all
  gather_facts: false

  tasks:
  
    - name: Run Infra validated AAP Configuraton as Code
      infra.aap_configuration.configure_aap.yml
