# vim:ft=ansible:
# setup namespaces/upload collections into containerized PAH
# turn verbose project syncing on
# call one of the collection things here
---
- name: Add user to EDA Controller
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    eda_validate_certs: false

  roles:
    - infra.aap_configuration.eda_users
