---
- name: Perform Actions On Linux User Account
  # we use AWS tagging to help identify our hosts
  hosts: tag_os_type_linux
  # we don't need any host facts, so disable to make run faster
  gather_facts: false

  tasks:

    - block:

        - name: Disable local UNIX user account
          user: name='{{firstname}}.{{surname}}' shell=/bin/false expires=0
          ignore_errors: true

      rescue:
        - debug: msg='Oops! Something went wrong - please investigate'

      always:
        - debug: msg='Tasks to disable UNIX user accounts have been run'

      tags:
        - deactivate

    - block:

        - name: Delete local UNIX user account
          user: name=name='{{firstname}}.{{surname}}' state=absent remove=yes
          ignore_errors: true

      rescue:
        - debug: msg='Oops! Something went wrong - please investigate'

      always:
        - debug: msg='Tasks to delete UNIX user accounts have been run'

      tags:
        - delete
