# vim:ft=ansible:
---
- hosts: all
  gather_facts: false

  vars:
    period: 300
    myfile: /var/tmp/mydata/write_file

  tasks:
    - name: I'm feeling real sleepy...
      ansible.builtin.wait_for:
        timeout: "{{ period }}"
      delegate_to: localhost


    - name: Read mounted file...
      ansible.builtin.debug:
        msg: "Read file... {{lookup('file', '/var/tmp/mydata/read_file') }}"
        
    - name: Write to a new file...
      ansible.builtin.copy:
        dest: "{{ myfile }}"
        content: |
        
          This is the file I've just written to.
          
          
