# vim:ft=ansible:
---
- hosts: all
  gather_facts: false

  vars:
    period: 120
    myfile: /var/tmp/mydata/file

  tasks:
    - name: I'm feeling real sleepy...
      ansible.builtin.wait_for:
        timeout: "{{ period }}"
      delegate_to: localhost

    - name: Read mounted file...
      ansible.builtin.debug:
        msg: "Read file... {{lookup('file', '{{ myfile }}_read') }}"
        
    - name: Write to a new file...
      ansible.builtin.copy:
        dest: "{{ myfile }}_write"
        content: |
        
          This is the file I've just written to.
          
          
