# vim:ft=ansible:
---
- hosts: all
  gather_facts: false

  vars:
    period: 120
    myfile: /var/tmp/mydata/file

  tasks:
    - name: "I'm feeling real sleepy..."
      ansible.builtin.wait_for:
        timeout: "{{ period }}"
      delegate_to: localhost

    - name: "Read pre-existing file..."
      ansible.builtin.debug:
        msg: "{{ lookup('file', '{{ myfile }}_read') }}"
        
    - name: "Write to a new file..."
      ansible.builtin.copy:
        dest: "{{ myfile }}_write"
        content: |
          \nThis is the file I've just written to.\n
          
     - name: "Read written out file..."
       ansible.builtin.debug:
         msg: "{{ lookup('file', '{{ myfile }}_write') }}"
          
          
