# vim:ft=ansible:
---
- hosts: all
  gather_facts: false

  vars:
    period: 300

  tasks:
    - name: I'm feeling real sleepy...
      ansible.builtin.wait_for:
        timeout: "{{ period }}"
      delegate_to: localhost


    - ansible.builtin.debug:
        msg: "Isolated paths mounted into execution node: {{ lookup('env', 'AWX_ISOLATION_SHOW_PATHS') }}"
