# vim:ft=ansible:
---
- hosts: all
  gather_facts: true
  become: yes

  vars:
    profile: xccdf_org.ssgproject.content_profile_pci-dss
    outdir: /vagrant
    outfile: "{{ inventory_hostname }}.html"
    results: "{{ outdir }}/{{ inventory_hostname }}-results.xml"
    outdest: "{{ outdir }}/{{ inventory_hostname }}-results.html"
    guide: /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
    wwwdir: /var/www/html/openscap

  tasks:

    - name: Install openSCAP packages on each node
      yum: name={{ item }} state=latest
      with_items:
        - openscap
        - openscap-utils
        - scap-security-guide
      when: ansible_distribution == 'RedHat'

    - name: Run oscap security check using {{ profile }}
      command: oscap xccdf eval --profile {{ profile }} --results {{ results }} --report {{ outdest }} {{ guide }}
      ignore_errors: true

    - name: Wait for report to finish
      wait_for: path={{ outdest }}
