---
- hosts: localhost

  tasks:
    - name: Grab a user record
      snow_record:
        username: xxxxx
        password: xxxxx
        instance: xxxxx
        state: present
        number: 7696f1d9dba963001fe855d0cf961995
        table: sys_user
        lookup_field: sys_id
