---
- hosts: localhost

  tasks:
    - name: Update an incident
      snow_record:
        username: admin
        password: S3rv1c3n0w
        instance: dev20070
        state: present
        number: INC0010009
        data:
          work_notes : "Update from Ansible Tower. Sweet."