---
- hosts: localhost
  gather_facts: false
  no_log: false

  vars:
    table: incident # can be change_reuest, incident

  tasks:
    - name: Update a ServiceNow record
      snow_record:
        state: present
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        table: "{{ table }}" 
        number: "{{ snow_record }}" 
        data:
          comments : "Update from Ansible Tower. Sweet."


