---
- hosts: localhost
  gather_facts: true

  tasks:
    - name: Create an incident
      snow_record:
        username: admin
        password: S3rv1c3n0w
        instance: dev20070
        state: present
        data:
          short_description: "This is a test incident opened by Ansible"
          severity: 3
          priority: 2
      register: new_incident
      no_log: true

