---
- hosts: localhost
  gather_facts: false
  no_log: false

  tasks:
    - name: Create a ServiceNow record
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        data:
          short_description: "This is a record opened using Ansible"
          severity: 3
          priority: 2
        table: incident # can be change_reuest, incident
      register: new_snow_record

    - debug: 
        var: new_snow_record.record.number
        verbosity: 1

    - name: "Save ServiceNow Record for updating"
      set_stats:
        data:
          snow_record:  "{{ new_snow_record.record.number }}"