- hosts: localhost

  vars:
    unsafe_writes:
      ANSIBLE_UNSAFE_WRITES: 1

  tasks:

    - name: Make a copy of a file inside the container
      ansible.builtin.copy:
        src: local_file_a
        dest: local_copy_a
      environment: "{{ unsafe_writes }}"
      delegate_to: localhost
